zvirata1 = set(["pes", "kocka", "kralik", "had"])
zvirata2 = set(["pes", "kocka", "andulka", "osel", "slepice"])
print((zvirata1) + (zvirata2))
print((zvirata1) - (zvirata2))
print((zvirata2) - (zvirata1))
